### ISSUE TITLE
Password protected .zip file support

### ISSUE THREAD

**Issue by Pureaznangel** [ravibpatel/AutoUpdater.NET#560] opened 2022-08-10 17:25 UTC
Please add support to password protected .zip file (display a dialogue to allow user to input license code/password (from developer) to unzip the update). thanks.

**Comment by ravibpatel** [comment] 2022-09-02 11:58
Duplicate of #74. As far as I know .NET doesn't provide this directly so if I want to add this feature then I need to rely on a third party library.

**Closed** 2022-09-03 08:43 UTC
