### ISSUE TITLE
DownloadUpdateDialog.cs - System.IndexOutOfRangeException at line 107

### ISSUE THREAD

**Issue by Lilium-Candidum** [ravibpatel/AutoUpdater.NET#454] opened 2021-04-06 12:31 UTC
This is the StackTrace:

`   at System.Net.Mime.MailBnfHelper.ReadToken(String data, Int32& offset, StringBuilder builder)
   at System.Net.Mime.ContentDisposition.ParseValue()
   at System.Net.Mime.ContentDisposition..ctor(String disposition)
   at AutoUpdaterDotNET.DownloadUpdateDialog.WebClientOnDownloadFileCompleted(Object sender, AsyncCompletedEventArgs asyncCompletedEventArgs) in C:\Source\NpControls_div\AutoUpdater.NET-master\AutoUpdater.NET-master\AutoUpdater.NET\DownloadUpdateDialog.cs:line 107`

It happens when I try to update to a new version.

**Comment by ravibpatel** [comment] 2021-04-06 12:35
Can you give me download URL you are using?

**Comment by Lilium-Candidum** [comment] 2021-04-06 12:50
I can't provide you with the link as it is confidential.

This is what I can provide:

_webClient.ResponseHeaders {Accept-Ranges: bytes\r\nETag: ... Last-Modified: Tue, 06 Apr 2021 10:30:26 GMT\r\nContent-Disposition: \r\n\r\n}

My ContentDisposition seems to be empty.

**Comment by ravibpatel** [comment] 2021-04-06 13:07
Can you try the directly linking to the file or moving it to another server?

**Comment by ravibpatel** [comment] 2022-09-02 12:05
Duplicate of #391. Are you able to solve the issue?

**Closed by ravibpatel** 2022-09-02 12:05 UTC
Labels: duplicate
